/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-04-15 04:31:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uboard.objects.Utilities;
import com.uboard.objects.Class;
import com.uboard.objects.Lesson;
import com.uboard.objects.Assignment;
import com.uboard.objects.Comment;
import com.uboard.interfaces.User;
import com.uboard.objects.Student;
import com.uboard.objects.Teacher;

public final class class_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Home - uBoard</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"/favicon.png\">\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/jquery-ui-1.10.4.min.css\">\r\n");
      out.write("        <script src=\"scripts/jquery-1.10.2.js\"></script>\r\n");
      out.write("        <script src=\"scripts/jquery-ui-1.10.4.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/master.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/class.css\">\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"scripts/home.js\"></script>\r\n");
      out.write("        <script src=\"scripts/class.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("            <!--\r\n");
      out.write("                JSP IMPLEMENTATION PSEUDOCODE\r\n");
      out.write("                \r\n");
      out.write("                Is the user logged in? {\r\n");
      out.write("                    -YES {\r\n");
      out.write("                        Redirect the user to search location (with no parameters, showing recent lessons/classes and highest rated lessons/classes)\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            -->\r\n");
      out.write("            \r\n");
      out.write("            ");

                Utilities util = Utilities.getInstance();
                User user           = null;
                
                Class object       = null;
                String title        = "";
                boolean isUser      = false;
                boolean isOwner     = false; 
                boolean isEnrolled  = false;
                
                try {
                    user = util.getOnlineUser(session.getId());
                } catch (Exception e){}
                
                if((title = request.getParameter("class_id")) != null){
                    object = new Class(Integer.parseInt(title));
                    if(object.classId == 0){
                        
      out.write("Class not found");

                        return;
                    }
                } else {
                    response.sendRedirect("/");
                    return;
                }
                
                if(user != null) {
                    isEnrolled = object.isEnrolled(user.getUsername());
                    isUser = true;
                    
                    if(user.getUsername().equals(object.createdBy)){
                        isOwner = true;
                    }
                }
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"top-banner\">\r\n");
      out.write("                <div id=\"top\">\r\n");
      out.write("                    <div id=\"search-box\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <input type=\"text\" id=\"content-search\" val=\"\" placeholder=\"Search\">\r\n");
      out.write("                            <img id=\"mag-glass\" />\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <a class=\"logo\" title=\"Take me to the Home Page!\" href=\"/\">\r\n");
      out.write("                        <img src=\"/images/logos/uboard_logo_side.png\" />\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"user-auth\">\r\n");
      out.write("                        ");
if(user != null) {
      out.write("\r\n");
      out.write("                            <div id=\"login\">\r\n");
      out.write("                                ");
if(user instanceof Teacher){
      out.write("\r\n");
      out.write("                                <img id=\"teacher-hover\" src=\"/images/login/teacher-auth-small.png\" /><span style=\"position:relative; top:15px;\">");
      out.print(user.getUsername());
      out.write("</span>\r\n");
      out.write("                                ");
} else {
      out.write("\r\n");
      out.write("                                <img id=\"user-hover\" src=\"/images/login/user-img.png\" /><span style=\"position:relative; top:15px;\">");
      out.print(user.getUsername());
      out.write("</span>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"logged-in\">\r\n");
      out.write("                                ");
if(user instanceof Teacher){
      out.write("\r\n");
      out.write("                                <div onclick=\"window.location = '/profile.jsp?username=");
      out.print(user.getUsername());
      out.write("'\"><img src=\"/images/login/teacher-auth-small-hover.png\"><p>View Profile</p></div>\r\n");
      out.write("                                    <div onclick=\"toggleModal('create-class-modal');\"><img src=\"/images/login/create-class.png\"><p>Create Class</p></div>\r\n");
      out.write("                                ");
} else {
      out.write("\r\n");
      out.write("                                    <div onclick=\"window.location = '/profile.jsp?username=");
      out.print(user.getUsername());
      out.write("'\"><img src=\"/images/login/view-profile.png\"><p>View Profile</p></div>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                                <div onclick=\"toggleModal('create-lesson-modal');\"><img src=\"/images/login/create-lesson.png\"><p>Create Lesson</p></div>\r\n");
      out.write("                                <div onclick=\"logout()\"><img src=\"/images/login/logout.png\"><p>Log Out</p></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
} else {
      out.write("\r\n");
      out.write("                            <div id=\"login\">\r\n");
      out.write("                                <span style=\"position:relative; top:15px;\">LOG IN</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"login-modal\">\r\n");
      out.write("                                <form id=\"login-form\">\r\n");
      out.write("                                    <input name=\"id\" type=\"text\" id=\"login-user\" class=\"text-input\" placeholder=\"Username\">\r\n");
      out.write("                                    <span id=\"login-user-pic\"></span>\r\n");
      out.write("                                    <input type=\"password\" id=\"login-pass\" class=\"text-input\" placeholder=\"Password\">\r\n");
      out.write("                                    <span id=\"login-pass-pic\"></span>\r\n");
      out.write("                                    <input id=\"login-button\" class=\"button\" type=\"submit\" value=\"LOG IN\">\r\n");
      out.write("                                    <a href=\"/register.jsp\"><input href=\"/register.jsp\" id=\"register-button\" class=\"button\" type=\"button\" value=\"REGISTER\" /></a>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div id=\"login-error\"><img src=\"/images/login/login-error.png\" style=\"position: relative; top: 2px; display: inline-block; width: 18px; margin: 0px;\"><p style=\"display: inline-block;color:  whitesmoke;line-height: 20px;margin: 0px 0px 0px 15px;\">Invalid login, please try again</p></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"bottom\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
if(isOwner) {
      out.write("\r\n");
      out.write("                <div id=\"edit-save\" class=\"edit-class\" onclick=\"saveClassData(");
      out.print(object.classId);
      out.write(");\"><p>Edit</p></div>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                <div id=\"class-side-tools\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"tool\">\r\n");
      out.write("                        <div id=\"enrolled\">\r\n");
      out.write("                            <h2>Enrolled</h2>\r\n");
      out.write("                            <p id=\"students-enrolled\">");
      out.print(object.numEnrolled);
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(object.enrollLimit);
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"tool\">\r\n");
      out.write("                        <div id=\"price\">\r\n");
      out.write("                            <h2>Price</h2>\r\n");
      out.write("                            <p>$<span class=\"class-price\">");
      out.print(object.price);
      out.write("</span></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
if(user != null && !isEnrolled && !isOwner) {
      out.write("\r\n");
      out.write("                    <div class=\"tool\">\r\n");
      out.write("                        <div id=\"class-enroll\" onclick=\"openEnrollModal();\">\r\n");
      out.write("                            <p id=\"enroll\">Enroll</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    ");
if(isEnrolled){
      out.write("\r\n");
      out.write("                    <div class=\"tool\">\r\n");
      out.write("                        <div id=\"class-stream\" onclick=\"window.location = 'stream.jsp?class_id=");
      out.print(object.classId);
      out.write("';\">\r\n");
      out.write("                            <p id=\"stream\">Stream Page</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    ");
if(isEnrolled || isOwner){
      out.write("\r\n");
      out.write("                    <div class=\"tool\">\r\n");
      out.write("                        <div id=\"assignments\">\r\n");
      out.write("                            <h2>Assignments</h2>\r\n");
      out.write("                            <div class=\"assignment\">\r\n");
      out.write("                                ");
int num = 0;
                                for(Assignment asign : object.assignments){
      out.write("\r\n");
      out.write("                                    <p class=\"assignment-title\" onclick=\"window.location = 'assignment.jsp?assignment_id=");
      out.print(asign.assignmentId);
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(++num);
      out.write('.');
      out.write(' ');
      out.print(asign.assignName);
      out.write("</p>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                                ");
if(isOwner) {
      out.write("\r\n");
      out.write("                                <div id=\"create-new-assignment\" onclick=\"toggleModal('create-assignment-modal');\">Create Assignment</div>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                    \r\n");
      out.write("                <div class=\"class-content\">\r\n");
      out.write("                    <div id=\"class-top\">\r\n");
      out.write("                        <div class=\"rating\" title=\"Total rating from lessons\">\r\n");
      out.write("                            <p class=\"positive-rating\">");
      out.print(object.posRating);
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"class-title\">\r\n");
      out.write("                            <h1>");
      out.print(object.className);
      out.write("</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"class-banner\">\r\n");
      out.write("                        <div id=\"teacher\">\r\n");
      out.write("                            <p id=\"teacher-name\" style=\"cursor: pointer;\" onclick=\"window.location = '/profile.jsp?username=");
      out.print(object.createdBy);
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(object.createdBy);
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    <div id=\"class-bottom\">\r\n");
      out.write("                        <div id=\"description\">\r\n");
      out.write("                            <h2>Class Description: </h2>\r\n");
      out.write("                            <textarea disabled id=\"class-desc\">");
      out.print(object.description);
      out.write("</textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"class-content\" id=\"lessons-created\" class=\"box\">\r\n");
      out.write("                    <div class=\"box-header\">\r\n");
      out.write("                        <h1>CLASS LESSONS</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-content\">\r\n");
      out.write("                        ");
for(Lesson lesson : object.lessons){
      out.write("\r\n");
      out.write("                        <div class=\"created-lesson\">\r\n");
      out.write("                            <div class=\"lesson-rating\">\r\n");
      out.write("                                ");
if(lesson.posRating >= 0) {
      out.write("\r\n");
      out.write("                                    <p class=\"positive-rating\">");
      out.print(lesson.posRating);
      out.write("</p>\r\n");
      out.write("                                    ");
} else {
      out.write("\r\n");
      out.write("                                    <p class=\"negative-rating\">");
      out.print(lesson.posRating);
      out.write("</p>\r\n");
      out.write("                                    ");
}
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"lesson.jsp?lesson_id=");
      out.print(lesson.lessonId);
      out.write('"');
      out.write('>');
      out.print(lesson.name);
      out.write("</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                        ");
if(isOwner) {
      out.write("\r\n");
      out.write("                            <div class=\"create-new-lesson\" onclick=\"toggleModal('create-lesson-class-modal');\">\r\n");
      out.write("                                <p>Create New Lesson</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"comments\" class=\"box\">\r\n");
      out.write("                    <div class=\"box-header\">\r\n");
      out.write("                        <h1>COMMENTS</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-content\" id=\"comment-section\">\r\n");
      out.write("                        ");
if(isEnrolled){
      out.write("\r\n");
      out.write("                        <div style=\"width: 100%; text-align: center;\"><div id=\"post-comment\" onclick=\"toggleModal('post-comment-modal');\">Comment</div></div>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                        ");
for(Comment comment : object.comments) {
      out.write("\r\n");
      out.write("                        <div class=\"comment\">\r\n");
      out.write("                            <div class=\"comment-user\"><img style=\"cursor: pointer;\" class=\"user\" onclick=\"window.location = '/profile.jsp?username=");
      out.print(comment.username);
      out.write("' \" src=\"/images/comments/user-comment.png\"></div>\r\n");
      out.write("                            <div class=\"comment-text\"><p style=\"cursor: pointer;\" class=\"user\" onclick=\"window.location = '/profile.jsp?username=");
      out.print(comment.username);
      out.write("' \">");
      out.print(comment.username);
      out.write("</p><p class=\"text\">");
      out.print(comment.text);
      out.write("</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
if(user != null){
      out.write("\r\n");
      out.write("            <div id=\"enroll-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Enroll</h2>\r\n");
      out.write("                <h2 style=\"margin:5px; text-align: center; display: inline-block; width: 15%;\">$<span class=\"class-price\">");
      out.print(object.price);
      out.write("</span></h2>\r\n");
      out.write("                <p style=\"display: inline-block; width: 75%;\">The amount stated will be charged to your PayPal account. Please confirm the transaction.</p>\r\n");
      out.write("                <br>\r\n");
      out.write("                <input type=\"button\" onclick=\"enroll('");
      out.print(object.classId);
      out.write("', '");
      out.print(user.getUsername());
      out.write("', '");
      out.print(user.getPaypalEmail());
      out.write("');\" value=\"Confirm\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('enroll-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"create-lesson-class-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Create New Class Lesson</h2>\r\n");
      out.write("                <p>Please fill out the following information to create a new lesson in this class.</p>\r\n");
      out.write("                <h4>Title</h4>\r\n");
      out.write("                <input type=\"text\" id=\"lesson-class-title\" placeholder=\"Lesson Title\">\r\n");
      out.write("                <input type=\"button\" onclick=\"createNewLesson('");
      out.print(user.getUsername());
      out.write("', $('#lesson-class-title').val(), '");
      out.print(object.classId);
      out.write("');\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('create-lesson-class-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"error-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Error</h2>\r\n");
      out.write("                <p>It seems you don't have a PayPal account set up yet. If you would like to set it up now, please click \"OK\".</p>\r\n");
      out.write("                <br>\r\n");
      out.write("                <input type=\"button\" onclick=\"redirectProfile('");
      out.print(user.getUsername());
      out.write("');\" value=\"Ok\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('error-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"create-lesson-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Create New Lesson</h2>\r\n");
      out.write("                <p>Please fill out the following information to create a new lesson.</p>\r\n");
      out.write("                <h4>Title</h4>\r\n");
      out.write("                <input type=\"text\" id=\"lesson-title\" placeholder=\"Lesson Title\">\r\n");
      out.write("                <input type=\"button\" onclick=\"createNewLesson('");
      out.print(user.getUsername());
      out.write("', $('#lesson-title').val(), 0);\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('create-lesson-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"create-class-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Create New Class</h2>\r\n");
      out.write("                <p>Please fill out the following information to create a new class.</p>\r\n");
      out.write("                <h4>Title</h4>\r\n");
      out.write("                <input type=\"text\" id=\"class-title\" placeholder=\"Class Title\">\r\n");
      out.write("                <h4>Price ($):</h4>\r\n");
      out.write("                <input type=\"text\" id=\"class-price\" placeholder=\"Class Price\">\r\n");
      out.write("                <h4>Class Enrollment Limit:</h4>\r\n");
      out.write("                <input type=\"text\" id=\"class-limit\" placeholder=\"Class Limit\">\r\n");
      out.write("                <input type=\"button\" onclick=\"createNewClass('");
      out.print(user.getUsername());
      out.write("', $('#class-title').val(), $('#class-price').val(), $('#class-limit').val());\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('create-class-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("               \r\n");
      out.write("            <div id=\"post-comment-modal\" class=\"box-modal\" style=\"top: 25%;\">\r\n");
      out.write("                <h2>Post New Comment</h2>\r\n");
      out.write("                <p>Please fill out the following information to post a new comment.</p>\r\n");
      out.write("                <h4>Text</h4>\r\n");
      out.write("                <textarea id=\"text-comment\" placeholder=\"Comment Text\" style=\"min-width: 96%; max-width: 96%; min-height: 500px; max-height: 500px;\"></textarea>\r\n");
      out.write("                <input type=\"button\" onclick=\"postNewComment('");
      out.print(user.getUsername());
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(object.classId);
      out.write(", 0);\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('post-comment-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("                        \r\n");
      out.write("            <div id=\"create-assignment-modal\" class=\"box-modal\" style=\"top: 25%;\">\r\n");
      out.write("                <h2>Create New Assignment</h2>\r\n");
      out.write("                <p>Please fill out the following information to create a new assignment.</p>\r\n");
      out.write("                <h4>Title</h4>\r\n");
      out.write("                <input type=\"text\" id=\"assignment-title\" placeholder=\"Assignment Title\">\r\n");
      out.write("                <h4>Description:</h4>\r\n");
      out.write("                <textarea style=\"box-sizing: border-box; padding: 10px; max-width: 100%; min-width: 100%; min-height: 400px; max-height: 400px\" id=\"assignment-description\" placeholder=\"Assignment Description\"></textarea>\r\n");
      out.write("                <input type=\"button\" onclick=\"createNewAssignment(");
      out.print(object.classId);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(user.getUsername());
      out.write("', $('#assignment-title').val(), $('#assignment-description').val());\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('create-assignment-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"modal\"></div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
