/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-03-26 23:42:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.BufferedReader;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Home - uBoard</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"/favicon.png\">\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/jquery-ui-1.10.4.min.css\">\r\n");
      out.write("        <script src=\"scripts/jquery-1.10.2.js\"></script>\r\n");
      out.write("        <script src=\"scripts/jquery-ui-1.10.4.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/master.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/profile.css\">\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"scripts/home.js\"></script>\r\n");
      out.write("        <script src=\"scripts/profile.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("            <!--\r\n");
      out.write("                JSP IMPLEMENTATION PSEUDOCODE\r\n");
      out.write("                \r\n");
      out.write("                Is the user logged in? {\r\n");
      out.write("                    -YES {\r\n");
      out.write("                        Is the user accessing his own profile? {\r\n");
      out.write("                        -YES {\r\n");
      out.write("                            Show special information only the user should know about\r\n");
      out.write("                            Enable Editing\r\n");
      out.write("                        }\r\n");
      out.write("                        -NO {\r\n");
      out.write("                            Show regular user information\r\n");
      out.write("                            Disable Editing\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("            \r\n");
      out.write("                   -NO {\r\n");
      out.write("                        Show regular user information\r\n");
      out.write("                        Disable Editing\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            -->\r\n");
      out.write("            <div id=\"top-banner\">\r\n");
      out.write("                <div id=\"top\">\r\n");
      out.write("                    <div id=\"search-box\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <input type=\"text\" id=\"content-search\" val=\"\" placeholder=\"Search\">\r\n");
      out.write("                            <img id=\"mag-glass\" />\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <a class=\"logo\" title=\"Take me to the Home Page!\" href=\"/\">\r\n");
      out.write("                        <img src=\"/images/logos/uboard_logo_side.png\" />\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"user-auth\">\r\n");
      out.write("                            <div id=\"login\">\r\n");
      out.write("                                <span style=\"position:relative; top:15px;\">LOG IN</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        <div id=\"login-modal\">\r\n");
      out.write("                            <form>\r\n");
      out.write("                                <input type=\"text\" id=\"login-user\" class=\"text-input\" placeholder=\"Username\">\r\n");
      out.write("                                <span id=\"login-user-pic\"></span>\r\n");
      out.write("                                <input type=\"password\" id=\"login-pass\" class=\"text-input\" placeholder=\"Password\">\r\n");
      out.write("                                <span id=\"login-pass-pic\"></span>\r\n");
      out.write("                                <input id=\"login-button\" class=\"button\" type=\"submit\" value=\"LOG IN\">\r\n");
      out.write("                                <a href=\"/register.jsp\"><input href=\"/register.jsp\" id=\"register-button\" class=\"button\" type=\"button\" value=\"REGISTER\" /></a>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"bottom\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"edit-save\" class=\"edit-profile\" onclick=\"saveUserData(this);\"><p>Edit</p></div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                <div id=\"user\" class=\"box\">\r\n");
      out.write("                    <div id=\"user-top\">\r\n");
      out.write("                        <img width=\"80\" id=\"student-image\" src=\"/images/profile/user.png\" />\r\n");
      out.write("                        <div id=\"user-info-top\">\r\n");
      out.write("                            <h2 id=\"username\">USERNAME</h2>\r\n");
      out.write("                            <div id=\"rating-box\">rating here</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"user-bottom\">\r\n");
      out.write("                        <h3>Name:</h3>\r\n");
      out.write("                        <p id=\"name\" class=\"edit\">First_Name Last_Name</p>\r\n");
      out.write("                        <h3>Email:</h3>\r\n");
      out.write("                        <p>Email@Email.com</p>\r\n");
      out.write("                        <h3>About:</h3>\r\n");
      out.write("                        <textarea id=\"about\" class=\"edit-area\" maxlength=\"500\" placeholder=\"Tell others about yourself!\" disabled></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"paypal\" class=\"box\">\r\n");
      out.write("                    <div class=\"box-header\">\r\n");
      out.write("                        <h1>PAYPAL</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-content\">\r\n");
      out.write("                        <h3>Paypal Registered Email:</h3>\r\n");
      out.write("                        <p id=\"paypal-email\" class=\"edit\" placeholder=\"Paypal account email\">Email@Email.com</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"lessons-created\" class=\"box\">\r\n");
      out.write("                    <div class=\"box-header\">\r\n");
      out.write("                        <h1>LESSONS CREATED</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-content\">\r\n");
      out.write("                        <div class=\"created-lesson\">\r\n");
      out.write("                            <div class=\"lesson-rating\">\r\n");
      out.write("                                <p class=\"positive-rating\">501</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"home.jsp\">Title of the Lesson goes in here (change to valid link)</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"created-lesson\">\r\n");
      out.write("                            <div class=\"lesson-rating\">\r\n");
      out.write("                                <p class=\"negative-rating\">-30</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"home.jsp\">Title of the Lesson goes in here (change to valid link)</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"classes-created\" class=\"box\">\r\n");
      out.write("                    <div class=\"box-header\">\r\n");
      out.write("                        <h1>CLASSES CREATED</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-content\">\r\n");
      out.write("                        <div class=\"created-class\">\r\n");
      out.write("                            <div class=\"class-rating\">\r\n");
      out.write("                                <p class=\"positive-rating\">15</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"home.jsp\">Title of the Lesson goes in here (change to valid link)</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"created-class\">\r\n");
      out.write("                            <div class=\"class-rating\">\r\n");
      out.write("                                <p class=\"negative-rating\">-30</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"home.jsp\">Title of the Lesson goes in here (change to valid link)</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"classes-taken\" class=\"box\">\r\n");
      out.write("                    <div class=\"box-header\">\r\n");
      out.write("                        <h1>CLASSES TAKEN</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-content\">\r\n");
      out.write("                        <div class=\"class-taken\">\r\n");
      out.write("                            <div class=\"class-rating\">\r\n");
      out.write("                                <p class=\"positive-rating\">15</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"home.jsp\">Title of the Lesson goes in here (change to valid link)</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"class-taken\">\r\n");
      out.write("                            <div class=\"class-rating\">\r\n");
      out.write("                                <p class=\"negative-rating\">-30</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"content-title\" href=\"home.jsp\">Title of the Lesson goes in here (change to valid link)</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>Classes Created go here.\r\n");
      out.write("                            Won't display if a user is looking at another user's profile\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
