/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-04-06 03:14:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uboard.objects.Utilities;
import com.uboard.interfaces.User;
import com.uboard.objects.Student;
import com.uboard.objects.Teacher;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Register - uBoard</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"/favicon.png\">\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/master.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/register.css\">\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/jquery-ui-1.10.4.min.css\">\r\n");
      out.write("        <script src=\"scripts/jquery-1.10.2.js\"></script>\r\n");
      out.write("        <script src=\"scripts/jquery-ui-1.10.4.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"scripts/home.js\"></script>\r\n");
      out.write("        <script src=\"scripts/register.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--\r\n");
      out.write("            /*\r\n");
      out.write("                JSP IMPLEMENTATION PSEUDOCODE\r\n");
      out.write("                \r\n");
      out.write("                Is the user logged in? {\r\n");
      out.write("                    -YES {\r\n");
      out.write("                        Redirect the user to his profile page (using user's username as an argument)\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("           */\r\n");
      out.write("        -->\r\n");
      out.write("        \r\n");
      out.write("            ");

                Utilities util = Utilities.getInstance();
                User user = null;
                
                try {
                    user = util.getOnlineUser(session.getId());
                } catch (Exception e){}
                
                //If the user is already active, then redirect the user to the homepage
                if(user != null){
                    String redirect = "";
                    
                    if(!request.getRequestURL().toString().contains("register.jsp"))
                        redirect = request.getRequestURL().toString();
                        
                    response.sendRedirect(redirect);
                    return;
                }
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"top-banner\">\r\n");
      out.write("                <div id=\"top\">\r\n");
      out.write("                    <div id=\"search-box\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <input type=\"text\" id=\"content-search\" val=\"\" placeholder=\"Search\">\r\n");
      out.write("                            <img id=\"mag-glass\" />\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <a class=\"logo\" title=\"Take me to the Home Page!\" href=\"/\">\r\n");
      out.write("                        <img src=\"/images/logos/uboard_logo_side.png\" />\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"user-auth\">\r\n");
      out.write("                        ");
if(user != null) {
      out.write("\r\n");
      out.write("                            <div id=\"login\">\r\n");
      out.write("                                ");
if(user instanceof Teacher){
      out.write("\r\n");
      out.write("                                <img id=\"teacher-hover\" src=\"/images/login/teacher-auth-small.png\" /><span style=\"position:relative; top:15px;\">");
      out.print(user.getUsername());
      out.write("</span>\r\n");
      out.write("                                ");
} else {
      out.write("\r\n");
      out.write("                                <img id=\"user-hover\" src=\"/images/login/user-img.png\" /><span style=\"position:relative; top:15px;\">");
      out.print(user.getUsername());
      out.write("</span>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"logged-in\">\r\n");
      out.write("                                ");
if(user instanceof Teacher){
      out.write("\r\n");
      out.write("                                <div onclick=\"window.location = '/profile.jsp?username=");
      out.print(user.getUsername());
      out.write("'\"><img src=\"/images/login/teacher-auth-small-hover.png\"><p>View Profile</p></div>\r\n");
      out.write("                                    <div onclick=\"toggleModal('create-class-modal');\"><img src=\"/images/login/create-class.png\"><p>Create Class</p></div>\r\n");
      out.write("                                ");
} else {
      out.write("\r\n");
      out.write("                                    <div onclick=\"window.location = '/profile.jsp?username=");
      out.print(user.getUsername());
      out.write("'\"><img src=\"/images/login/view-profile.png\"><p>View Profile</p></div>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                                <div onclick=\"toggleModal('create-lesson-modal');\"><img src=\"/images/login/create-lesson.png\"><p>Create Lesson</p></div>\r\n");
      out.write("                                <div onclick=\"logout()\"><img src=\"/images/login/logout.png\"><p>Log Out</p></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
} else {
      out.write("\r\n");
      out.write("                            <div id=\"login\">\r\n");
      out.write("                                <span style=\"position:relative; top:15px;\">LOG IN</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"login-modal\">\r\n");
      out.write("                                <form id=\"login-form\">\r\n");
      out.write("                                    <input name=\"id\" type=\"text\" id=\"login-user\" class=\"text-input\" placeholder=\"Username\">\r\n");
      out.write("                                    <span id=\"login-user-pic\"></span>\r\n");
      out.write("                                    <input type=\"password\" id=\"login-pass\" class=\"text-input\" placeholder=\"Password\">\r\n");
      out.write("                                    <span id=\"login-pass-pic\"></span>\r\n");
      out.write("                                    <input id=\"login-button\" class=\"button\" type=\"submit\" value=\"LOG IN\">\r\n");
      out.write("                                    <a href=\"/register.jsp\"><input href=\"/register.jsp\" id=\"register-button\" class=\"button\" type=\"button\" value=\"REGISTER\" /></a>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div id=\"login-error\"><img src=\"/images/login/login-error.png\" style=\"position: relative; top: 2px; display: inline-block; width: 18px; margin: 0px;\"><p style=\"display: inline-block;color:  whitesmoke;line-height: 20px;margin: 0px 0px 0px 15px;\">Invalid login, please try again</p></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"bottom\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                <div class=\"content-box\">\r\n");
      out.write("                    <h1>REGISTER</h1>\r\n");
      out.write("                    <form id=\"register\">\r\n");
      out.write("                        <p>Username: </p>\r\n");
      out.write("                        <input id=\"u-username\" type=\"text\" name=\"username\" placeholder=\"Username\" />\r\n");
      out.write("                        <p>Full Name:</p>\r\n");
      out.write("                        <input id=\"u-name\" type=\"text\" name=\"name\" placeholder=\"Full Name\" />\r\n");
      out.write("                        <p>Email:</p>\r\n");
      out.write("                        <input id=\"u-email\" type=\"email\" name=\"email\" placeholder=\"Email\"/>\r\n");
      out.write("                        <p>Password:</p>\r\n");
      out.write("                        <input id=\"u-password\" type=\"password\" name=\"password\" placeholder=\"Password\"/>\r\n");
      out.write("                        <input type=\"submit\" value=\"Submit\" />\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"create-lesson-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Create New Lesson</h2>\r\n");
      out.write("                <p>Please fill out the following information to create a new lesson.</p>\r\n");
      out.write("                <h4>Title</h4>\r\n");
      out.write("                <input type=\"text\" id=\"lesson-title\" placeholder=\"Lesson Title\">\r\n");
      out.write("                <input type=\"button\" onclick=\"createNewLesson();\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('create-lesson-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("             <div id=\"create-class-modal\" class=\"box-modal\">\r\n");
      out.write("                <h2>Create New Class</h2>\r\n");
      out.write("                <p>Please fill out the following information to create a new class.</p>\r\n");
      out.write("                <h4>Title</h4>\r\n");
      out.write("                <input type=\"text\" id=\"class-title\" placeholder=\"Class Title\">\r\n");
      out.write("                <h4>Price ($):</h4>\r\n");
      out.write("                <input type=\"text\" id=\"class-price\" placeholder=\"Class Price\">\r\n");
      out.write("                <h4>Class Enrollment Limit:</h4>\r\n");
      out.write("                <input type=\"text\" id=\"class-limit\" placeholder=\"Class Limit\">\r\n");
      out.write("                <input type=\"button\" onclick=\"createNewLesson();\" value=\"Create\">\r\n");
      out.write("                <input type=\"button\" onclick=\"toggleModal('create-class-modal');\" value=\"Cancel\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"modal\"></div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
